[project]
name = "5-deployment"
version = "0.1.0"
description = "churn prediction service"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scikit-learn>=1.7.2",
    "fastapi>=0.121.1", 
    "uvicorn>=0.38.0",
]

[dependency-groups]
dev = [
    "requests>=2.32.5"
]
